import Link from "next/link";
import type { ReactNode } from "react";

type Accent = "navy" | "blue" | "purple" | "orange" | "teal" | "green" | "red";
export type ScopeMetric = { label: string; value: string | number; foot: string; accent: Accent; icon?: ReactNode };
export type ScopeAction = { href: string; title: string; description: string; cta: string; accent: Accent; icon?: ReactNode };
export type ScopeTable = { title: string; subtitle: string; headers: string[]; rows: (string | number | ReactNode)[][] };

const accents: Record<Accent, { line: string; icon: string; bg: string }> = {
  navy: { line: "#0B3067", icon: "#0B3067", bg: "#EAF0FB" }, blue: { line: "#4565E8", icon: "#4565E8", bg: "#EAF0FB" }, purple: { line: "#A100F2", icon: "#A100F2", bg: "#F1E8FD" }, orange: { line: "#EC7600", icon: "#EC7600", bg: "#FDF0E4" }, teal: { line: "#009B8E", icon: "#009B8E", bg: "#E6F7F5" }, green: { line: "#00B86B", icon: "#00B86B", bg: "#E7F8EF" }, red: { line: "#F0002E", icon: "#F0002E", bg: "#FDEDEC" },
};

export default function ScopeDashboard({ scope, title, description, metrics, coverageTitle, coverageSubtitle, coverage, actions, table, children }: { scope: string; title: string; description: string; metrics: ScopeMetric[]; coverageTitle: string; coverageSubtitle: string; coverage: ScopeMetric[]; actions: ScopeAction[]; table?: ScopeTable; children?: ReactNode }) {
  return <main className="mx-auto w-full max-w-380 pb-12">
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-[12px] font-bold uppercase tracking-[0.08em] text-[#F0002E]"><span className="h-2 w-2 rounded-sm bg-[#F0002E]" />{scope}</p><h1 className="mt-2 text-[29px] font-extrabold tracking-tight text-[#101828]">{title}</h1><p className="mt-1.5 max-w-180 text-sm leading-relaxed text-[#667085]">{description}</p></div><div className="flex gap-2.5 pb-0.5"><Link href="/" className="inline-flex items-center gap-2 rounded-lg border border-[#D0D5DD] bg-white px-4 py-2.5 text-[13px] font-semibold text-[#101828] hover:bg-[#FAFBFC]">View Overview</Link><Link href="#analytics" className="inline-flex items-center gap-2 rounded-lg bg-[#281078] px-4 py-2.5 text-[13px] font-semibold text-white hover:bg-[#1D0B5D]">Open Full Analytics</Link></div></header>
    <Section title={scope === "Central Administration" ? "National Statistics" : `${scope} Statistics`} subtitle="Official administrative structure + live platform counts" /><div className="grid gap-3.5 sm:grid-cols-2 xl:grid-cols-5">{metrics.map((metric) => <Metric key={metric.label} {...metric} />)}</div>
    {children}
    <Section title={coverageTitle} subtitle={coverageSubtitle} /><div className="grid gap-3.5 sm:grid-cols-2 xl:grid-cols-4">{coverage.map((metric) => <Metric key={metric.label} {...metric} />)}</div>
    <Section title="Quick Actions" subtitle={`Frequently used ${scope} tools`} /><div className="grid gap-3.5 sm:grid-cols-2 xl:grid-cols-4">{actions.map((action) => <Action key={action.title} {...action} />)}</div>
    {table ? <><Section title={table.title} subtitle={table.subtitle} /><Panel className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-190 border-collapse text-[13px]"><thead><tr>{table.headers.map((header) => <th key={header} className="header-cell text-left">{header}</th>)}</tr></thead><tbody>{table.rows.map((row, index) => <tr key={index} className="hover:bg-[#FAFBFC]">{row.map((cell, cellIndex) => <td key={cellIndex} className="table-cell">{cell}</td>)}</tr>)}</tbody></table></div></Panel></> : null}
    <footer className="mt-5 border-t border-[#EAECF0] pt-4 text-[11.5px] text-[#98A2B3]">{scope} Portal · Data refreshed every 15 minutes · Analytical view only</footer>
  </main>;
}

export function Section({ title, subtitle }: { title: string; subtitle: string }) { return <div className="mb-3 mt-7"><h2 className="flex items-center gap-2 text-lg font-bold text-[#101828]"><span className="h-2 w-2 rounded-sm bg-[#F0002E]" />{title}</h2><p className="mt-1 text-sm text-[#98A2B3]">{subtitle}</p></div>; }
export function Panel({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`rounded-[10px] border border-[#DDE2EA] bg-white shadow-[0_1px_3px_rgba(16,24,40,0.08)] ${className}`}>{children}</div>; }
function Metric({ label, value, foot, accent, icon }: ScopeMetric) { const style = accents[accent]; return <article className="relative min-h-38 overflow-hidden rounded-[10px] border border-[#DDE2EA] bg-white px-4.5 py-4.5 shadow-[0_2px_5px_rgba(16,24,40,0.10)]"><span className="absolute inset-x-0 top-0 h-0.75 rounded-t-[10px]" style={{ backgroundColor: style.line }} /><div className="flex items-start justify-between gap-2"><p className="max-w-32 text-[12px] font-semibold leading-[1.35] text-[#667085]">{label}</p><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-lg font-bold" style={{ backgroundColor: style.bg, color: style.icon }}>{icon ?? "•"}</span></div><p className="mt-4 text-[29px] font-extrabold leading-none tracking-tight text-[#101828]">{value}</p><p className="mt-3.5 text-[11.5px] font-medium leading-4 text-[#98A2B3]">{foot}</p></article>; }
function Action({ href, title, description, cta, accent, icon }: ScopeAction) { const style = accents[accent]; return <Link href={href} className="flex min-h-43.5 flex-col rounded-[10px] border border-[#DDE2EA] bg-white p-4 shadow-[0_1px_3px_rgba(16,24,40,0.08)] transition hover:-translate-y-0.5 hover:shadow-md"><span className="flex h-9 w-9 items-center justify-center rounded-lg text-lg font-bold" style={{ backgroundColor: style.bg, color: style.icon }}>{icon ?? "•"}</span><p className="mt-3 text-[13.5px] font-bold text-[#101828]">{title}</p><p className="mt-2 text-[11.5px] leading-snug text-[#98A2B3]">{description}</p><p className="mt-auto pt-4 text-[11.5px] font-bold text-[#F0002E]">{cta}</p></Link>; }
